name: Build Sudoku macOS App
on: [push]  # Triggers on every git push

jobs:
  build:
    runs-on: macos-latest  # Uses a free macOS runner
    steps:
      # 1. Check out your code
      - uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Match your Python version

      # 3. Install Pygame and PyInstaller
      - name: Install dependencies
        run: pip install pygame pyinstaller

      # 4. Build the .app with PyInstaller
      - name: Build macOS App
        run: |
          export ARCHFLAGS="-arch x86_64"
          pyinstaller --name 'Sudoku' --windowed --icon 'sudoku.icns' sudoku.py

      # 5. Upload the .app as a downloadable artifact
      - name: Upload Sudoku App
        uses: actions/upload-artifact@v4
        with:
          name: Sudoku.app
          path: dist/Sudoku.app
